name: "@ubiquity-os-marketplace/daemon-pull-review"
description: "Autoamtically reviews pull requests on issues that are ready for review"

inputs:
  stateId:
    description: "State Id"
  eventName:
    description: "Event Name"
  eventPayload:
    description: "Event Payload"
  settings:
    description: "Settings"
  authToken:
    description: "Auth Token"
  ref:
    description: "Ref"
  signature:
    description: "Signature sent from the Kernel"
  command:
    description: "Command"

outputs:
  result:
    description: "The review of the pull request"
    value: ${{ steps.main.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Run compute reviews
      id: main
      shell: bash
      run: |
        node dist/index.js
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}