name: Formatting Check

on:
  push:
  pull_request:

jobs:
  format-check:
    name: Check for formatting errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cspell
        run: bunx cspell "**/*"

      - name: Prettier
        run: bunx prettier --check .
