name: Update Manifest and Commit Changes

on:
  workflow_dispatch:
  push:

jobs:
  update-manifest:
    name: "Update Manifest and Commit Changes"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Update Manifest and Commit Changes
        uses: ubiquity-os/action-deploy-plugin@main

        with:
          treatAsEsm: false
          sourcemap: false
          pluginEntry: ${{ github.workspace }}/src/main.ts
          commitMessage: "chore: updated manifest.json and dist build"
          nodeVersion: "20.10.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
